#!/usr/bin/env bash
# Installs Nginx and configures a web server

# Exit on any error
set -e

# Install Nginx (update first)
apt-get update -y
apt-get install nginx -y

# Ensure Nginx starts (systemctl not allowed)
service nginx start

# Replace default index page with "Hello World!"
echo 'Hello World!' > /var/www/html/index.html

