#!/usr/bin/env bash
# Installs Nginx and configures a 301 redirect from /redirect_me to a YouTube video

set -e

# Install Nginx
apt-get update -y
apt-get install nginx -y

# Start Nginx service
service nginx start

# Add the redirect rule using sed to modify the default config
sed -i '/^\tlocation \/ {/a \ \ \ \ location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Reload Nginx to apply the change
service nginx reload
